import json
import uuid
import subprocess
from datetime import datetime

class ReportGenerator:
    def __init__(self, db_cli="team-db"):
        self.db_cli = db_cli

    def _run_db_cmd(self, sql):
        import time
        max_retries = 5
        for i in range(max_retries):
            result = subprocess.run([self.db_cli, sql], capture_output=True, text=True)
            if result.returncode == 0:
                return json.loads(result.stdout) if result.stdout.strip() else []
            if "locked" in result.stderr.lower() and i < max_retries - 1:
                time.sleep(1)
                continue
            raise Exception(f"Database error: {result.stderr}")

    def persist_invoice(self, data):
        invoice_id = str(uuid.uuid4())
        meta = data.get("invoice_metadata", {})
        
        # Persist invoice
        sql = f"""
        INSERT INTO audit_invoices (id, vendor_name, invoice_number, invoice_date, total_amount, currency, extraction_json)
        VALUES ('{invoice_id}', '{meta.get("vendor_name")}', '{meta.get("invoice_number")}', '{meta.get("invoice_date")}', 
                {meta.get("total_amount", 0)}, '{meta.get("currency", "USD")}', '{json.dumps(data).replace("'", "''")}')
        """
        self._run_db_cmd(sql)

        # Persist compliance flags
        for flag in data.get("compliance_results", []):
            flag_id = str(uuid.uuid4())
            sql = f"""
            INSERT INTO audit_compliance_flags (id, invoice_id, flag_type, description, estimated_savings, severity)
            VALUES ('{flag_id}', '{invoice_id}', '{flag.get("flag_type")}', '{flag.get("description").replace("'", "''")}', 
                    {flag.get("estimated_savings", 0)}, '{flag.get("severity")}')
            """
            self._run_db_cmd(sql)
        
        return invoice_id

    def generate_markdown_report(self, data):
        meta = data.get("invoice_metadata", {})
        flags = data.get("compliance_results", [])
        
        # Sort flags by estimated savings to find top 3
        sorted_flags = sorted(flags, key=lambda x: x.get("estimated_savings", 0), reverse=True)
        top_3 = sorted_flags[:3]
        total_potential_savings = sum(f.get("estimated_savings", 0) for f in flags)

        report = []
        report.append(f"# HVAC Invoice Audit Report - {meta.get('invoice_number', 'N/A')}")
        report.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d')}")
        report.append(f"**Vendor:** {meta.get('vendor_name', 'N/A')}")
        report.append(f"**Invoice Total:** {meta.get('currency', 'USD')} {meta.get('total_amount', 0):,.2f}")
        report.append(f"\n## Summary")
        report.append(f"We identified **{len(flags)}** compliance flags with a total potential cost recovery of **{meta.get('currency', 'USD')} {total_potential_savings:,.2f}**.")
        
        report.append(f"\n## Top 3 Cost-Recovery Opportunities")
        if not top_3:
            report.append("No significant cost-recovery opportunities identified.")
        for i, flag in enumerate(top_3, 1):
            report.append(f"### {i}. {flag.get('flag_type')}")
            report.append(f"- **Estimated Savings:** {meta.get('currency', 'USD')} {flag.get('estimated_savings', 0):,.2f}")
            report.append(f"- **Severity:** {flag.get('severity', 'N/A').capitalize()}")
            report.append(f"- **Details:** {flag.get('description')}")

        report.append(f"\n## All Compliance Flags")
        if not flags:
            report.append("No compliance flags found.")
        else:
            report.append("| Flag Type | Severity | Estimated Savings | Description |")
            report.append("|-----------|----------|-------------------|-------------|")
            for flag in flags:
                report.append(f"| {flag.get('flag_type')} | {flag.get('severity').capitalize()} | {meta.get('currency', 'USD')} {flag.get('estimated_savings', 0):,.2f} | {flag.get('description')} |")

        report.append(f"\n## Invoice Metadata")
        report.append(f"- **Invoice Date:** {meta.get('invoice_date', 'N/A')}")
        report.append(f"- **Audit Status:** Completed")
        report.append(f"- **Audit ID:** {str(uuid.uuid4())[:8].upper()}")

        report.append(f"\n---")
        report.append(f"*Disclaimer: This report is generated by an automated audit pipeline. Estimated savings are based on typical market rates and contract rules. Please verify with your service provider before taking action.*")

        return "\n".join(report)

if __name__ == "__main__":
    # Test with sample data
    sample_data = {
        "invoice_metadata": {
            "vendor_name": "Arctic Cool HVAC Services",
            "invoice_number": "INV-2023-001",
            "invoice_date": "2023-05-15",
            "total_amount": 1250.00,
            "currency": "USD"
        },
        "extraction_data": {
            "line_items": [
                {"description": "Labor - Regular Rate", "quantity": 5, "unit_price": 150, "total": 750},
                {"description": "Filter Replacement", "quantity": 2, "unit_price": 250, "total": 500}
            ]
        },
        "compliance_results": [
            {
                "flag_type": "Overcharge",
                "description": "Labor rate exceeds contract maximum of $120/hr.",
                "estimated_savings": 150.00,
                "severity": "high"
            },
            {
                "flag_type": "Vague Billing",
                "description": "Filter replacement cost is significantly higher than market average ($50-100). No part numbers provided.",
                "estimated_savings": 300.00,
                "severity": "medium"
            },
            {
                "flag_type": "Premium Rate Discrepancy",
                "description": "Work performed during regular hours but billed at premium rate.",
                "estimated_savings": 50.00,
                "severity": "low"
            }
        ]
    }
    
    gen = ReportGenerator()
    invoice_id = gen.persist_invoice(sample_data)
    print(f"Persisted invoice with ID: {invoice_id}")
    
    report_md = gen.generate_markdown_report(sample_data)
    with open(f"report_{sample_data['invoice_metadata']['invoice_number']}.md", "w") as f:
        f.write(report_md)
    print(f"Generated report: report_{sample_data['invoice_metadata']['invoice_number']}.md")
